version: '3.1'

services:

  app:
    container_name: bookmedik
    image: sergioib94/bookmedik:v1
    restart: always
    environment:
      DB_HOST: db
      DB_USER: admin
      DB_PASSWORD: admin
      DB_NAME: bookmedik
    ports:
      - 80:8080
    volumes:
      - /home/sergioib/Escritorio/Informatica/Github/bookmedik/vol-app:/var/log/apache2

  db:
    container_name: servidor_mysql
    image: mariadb
    restart: always
    environment:
      MYSQL_DATABASE: bookmedik
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_ROOT_PASSWORD: bookmedik_admin
    volumes:
      - /home/sergioib/Escritorio/Informatica/Github/bookmedik/vol-maria:/var/lib/mysql
